[tool.poetry]
name = "hello-python"
version = "0.1.0"
description = ""
authors = ["RenYan Wei <weirenyan@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
#test = " python -m unittest discover -s tests"